### ISSUE TITLE
Source code unavailable

### ISSUE THREAD

**Issue by rien** [openphotogrammetry/colmap-cl#4]
Can you add the source code to this repository? For a organisation "openphotogrammetry" it makes little sense to keep the source code closed?

**Comment by 3D-360** [comment]
We have contributed to the CUDA versioin of Colmap. 

"Open" has many interpretations.  We are currently focused on the openness of hardware.  Isn't it nice that Colmap runs on AMD GPUs now?  We will probably release our code at some time in the future.

**Comment by ssorgatem** [comment]
Openness of hardware?
But you aren't developing any hardware, right?

If you want to keep it closed-source and proprietary, that's your right, but calling it "open" or having it under "openphotogrammetry" is certainly misleading.

**Comment by 3D-360** [comment]
Maybe OpenPhotogrammetry is a confusing name.  It seems like a gray area to me:

- Our code is based on Open Source Colmap
- We are following Colmap's BSD license which is a low restriction type of license for open source software
- We are based on OpenCL that runs on more hardware than CUDA software
- We will probably release our code in the future, but it may be months.

Unfortunately we do not have the the resources to easily separate our proprietary code from the part that we want to make public.  Packaging up and debugging a Windows binary takes time, and we have already spent more weeks than initially anticipated.  We could have kept it to ourselves, but I wanted to give something back to the Colmap world.  Please enjoy what we have made, and don't get hung up on semantics.

**Comment by ssorgatem** [comment]
Well, iOS and OSX for instance are also based on BSD-licensed open-source code and don't call themselves "open" because of it (and rightly so).

Unfortunately I personally cannot enjoy it yet because it only works on Windows and doesn't seem to work in wine.

**Comment by rien** [comment]
@3D-360 thank you for clearing up the confusion. If it is the desire of your organization to keep the source code secret, there is nobody who can tell you you can't with the BSD license. Although I do also think the name OpenPhotogrammetry is currently misleading, it is not something that is protected either.

I think the main frustration here is that the executable is windows-only. There are plenty of folks out there, including me, who would like to fix the source code to compile for Linux. However, that is currently impossible since we do not have the source code to start with.

Anyway thank you for considering to open-source (part of) your fork. I will be looking forward to it and would be happy to contribute to make your fork work on linux systems.

**Comment by 3D-360** [comment]
I do appreciate ssorgatem & rien's interest in our project.  
Your interest may speed up our plans to release the code for Linux.
We develop in Linux.

**Comment by SchmollTroll** [comment]
Any maybe a macOS version? Would be great!

**Comment by 3D-360** [comment]
Schmoll,

I was an Apple fan starting with the first Mac in 1984, but some of their choices lately make development difficult.  For example, Apple is dropping OpenCL:

> Important: OpenCL was deprecated in macOS 10.14. To create high-performance code on GPUs, use the Metal framework instead. See Metal.https://developer.apple.com/library/archive/documentation/Performance/Conceptual/OpenCL_MacProgGuide/Introduction/Introduction.html

We develop in Linux/Ubuntu 20.04, and we port to Windows because of its market share.  Because this project is focused on OpenCL, I doubt that we will be porting to Apple.

**Comment by pwhelan** [comment]
Is this code already merged into upstream?

**Comment by revisionarian** [comment]
> Is this code already merged into upstream?

@pwhelan, no the COLMAP-CL code has not yet been merged into the original COLMAP codebase.
